apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xxl-job
  name: xxl-job
  namespace: ypdan
spec:
  selector:
    matchLabels:
      app: xxl-job
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: xxl-job
        version: v1.0.1
    spec:
      containers:
        - env:
            - name: PARAMS
              value: --spring.datasource.url=jdbc:mysql://xxx.com:3306/xxl-job?autoReconnect=true&tinyInt1isBit=false&useUnicode=true&charset=utf8mb4&collation=utf8_general_ci&useSSL=false&characterEncoding=UTF-8  --spring.datasource.username=root  --spring.datasource.password=zm2018  --xxl.job.login.username=admin  --xxl.job.login.password=ypdan2018  --xxl.job.accessToken=ypdan2018
          image: xuxueli/xxl-job-admin:2.0.1
          name: xxl-job
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /data/applogs
              name: xxl-job-claim0
      restartPolicy: Always
      volumes:
        - name: xxl-job-claim0
          persistentVolumeClaim:
            claimName: xxl-job-claim0

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: xxl-job
  name: xxl-job
  namespace: ypdan
spec:
  ports:
    - port: 9003
      targetPort: 8080
  #      nodePort: 30001
  #  type: NodePort
  selector:
    app: xxl-job

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: xxl-job-claim0
  name: xxl-job-claim0
  namespace: ypdan
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi