#  配置共享文件系统NFS
#  创建PV和PVC
#  创建ConfigMap
#  创建Headless Service
#  创建StatefulSet
#  初始化redis集群
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: ypdan
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        version: v1.0.1
    spec:
      containers:
        - image: redis:5.0.4-alpine3.9
          name: redis
          ports:
            - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: ypdan
spec:
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis
  type: NodePort
