apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ypdan
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend
        version: v1.0.1
    spec:
      containers:
        - name: frontend
          image: registry.cn-shenzhen.aliyuncs.com/zm-dev/ypdan-admin:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          imagePullPolicy: Always
      imagePullSecrets:
        - name: registry-secret

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: ypdan
spec:
  ports:
    - name: TCP
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

  selector:
    app: frontend
